### PR TITLE
fix: Use of undefined variables

### PR DESCRIPTION
**Pull request by epage**
For now, cobalt is becoming stricter on the user of undefined variables to help catch problems when migrating sites through https://github.com/cobalt-org/cobalt.rs/pull/346.

With this PR, your site correctly builds against 346 after running `cobalt migrate`.  Hopefully my guesses for how to change your site are close enough :).

I will follow up with a PR that migrates your site once 346 is dev complete.  Feel free to start playing with it and providing feedback (particularly around https://github.com/cobalt-org/cobalt.rs/issues/323).

Its unclear what method you are using for deployment.  I'd recommend ensuring that it locks down the version of cobalt used.

### CODE REVIEW

**Comment by badboy** [comment]
Thanks! 
It does remove the date display though. Was that intented?
What does the `route` variable does?

Deployment uses a fixed installed version of cobalt, so it’s `locked down`

**Comment by epage** [comment]
> What does the route variable does?

Your menu snippet uses `route` to specially highlight which section of the site you are in.

See https://github.com/badboy/fnordig.de/blob/master/_layouts/_menu.liquid

> It does remove the date display though. Was that intented?

If I understood your site correctly, I removed it from `_layouts/simple.liquid` which looks like its used on pages that don't have a `date`.  It still exists on `_layouts/posts.liquid`.

So before my change, I think you have pages that have `<time pubdate="pubdate"></time><br />`

For example, see `view-source:https://fnordig.de/posts/`

**Comment by badboy** [comment]
Oh right, completely forgot that I did define that :D 
I'm gonna take a look, apply it locally and if everything goes as planned I'll merge it. Thanks!

**Comment by epage** [comment]
Updated for your latest blog post

**Comment by badboy** [comment]
Happy new year, @epage!
Completely forgot that I never merged this. Will keep it open and do the merge tomorrow.

**Comment by epage** [comment]
v0.11 is now released

**Pull request merged**
