### PR TITLE
fix: Upgrade to cobalt #346

### PR DESCRIPTION
**Pull request by epage**
*DO NOT MERGE THIS YET* The PR is not yet merged or released.  I'm posting PRs for all known cobalt blogs.  After that, I'll try to give a feedback window before merging the PR and creating a release.

Feedback on https://github.com/cobalt-org/cobalt.rs/pull/346 is welcome.  In addition to this PR, you can peruse the updated [documentation](https://cobalt-org.github.io/).

Commands run
- `cobalt migrate`
- `rm _includes/default.liquid`
- `rm _includes/post.liquid`
- `rm _includes/simple.liquid`
- `rm _layouts/_*.liquid`

Includes https://github.com/badboy/fnordig.de/pull/4

### CODE REVIEW

**Comment by badboy** [comment]
Meanwhile I merged #4, but this still seems to apply cleanly. I'll wait for upstream then

**Comment by badboy** [comment]
Is this released already?

**Comment by badboy** [comment]
I have a ready-to-go PR in #6 based on latest master.

**Comment by epage** [comment]
v0.11 is now released

**Pull request closed without merging**
